Add systemd-based lab variants for single-node, multi-node, and standby/mirror setups

diff --git a/WarehousePG6-from-source-RH7-single-node-systemd/Dockerfile b/WarehousePG6-from-source-RH7-single-node-systemd/Dockerfile
--- a/WarehousePG6-from-source-RH7-single-node-systemd/Dockerfile
+++ b/WarehousePG6-from-source-RH7-single-node-systemd/Dockerfile
@@ -8,8 +8,14 @@ ARG GLOB_IMAGE_TITLE="WarehousePG"
 ARG GLOB_IMAGE_DESCRIPTION="WarehousePG Database image"
 ARG GLOB_IMAGE_VERSION="0.1.1"
 ARG GLOB_IMAGE_AUTHORS="andreas.scherbaum@enterprisedb.com"
+ARG GLOB_WHPG_BUILD_DIR=/opt/warehousepg-build
+ARG GLOB_WHPG_INSTALL_DIR_PARENT=/usr/local
+ARG GLOB_WHPG_INSTALL_DIR_NAME=greenplum-db
+ARG GLOB_WHPG_INSTALL_DIR=$GLOB_WHPG_INSTALL_DIR_PARENT/$GLOB_WHPG_INSTALL_DIR_NAME
+ARG GLOB_WHPGHOME=${GLOB_WHPG_INSTALL_DIR}
 ARG GLOB_MASTER_DATA_DIRECTORY=/whpgdata/master/whpgsne-1
-ARG GLOB_WHPGHOME="/usr/local/greenplum-db"
+ARG GLOB_WHPG_REPO_URL=https://github.com/warehouse-pg/warehouse-pg.git
+ARG GLOB_WHPG_REPO_TAG=WHPG_6X_STABLE
 
 
 #######################################################################
@@ -26,13 +32,15 @@ ARG GLOB_IMAGE_AUTHORS
 ARG GLOB_OS_NAME
 ARG GLOB_OS_VERSION
 ARG GLOB_BUILD_VERSION
+ARG GLOB_WHPG_REPO_URL
+ARG GLOB_WHPG_REPO_TAG
+ARG GLOB_WHPG_BUILD_DIR
+ARG GLOB_WHPG_INSTALL_DIR_PARENT
+ARG GLOB_WHPG_INSTALL_DIR_NAME
+ARG GLOB_WHPG_INSTALL_DIR
 ARG GLOB_WHPGHOME
 #ARG LD_LIBRARY_PATH
 ARG GLOB_MASTER_DATA_DIRECTORY
-
-# from commandline arguments
-ARG EDBTOKEN
-ARG EDBREPOSITORY
 
 # metadata
 LABEL maintainer=$GLOB_MAINTAINER
@@ -48,6 +56,12 @@ LABEL org.opencontainers.image.authors=$GLOB_IMAGE_AUTHORS
 ENV LANG=en_US.UTF-8
 ENV LC_ALL=en_US.UTF-8
 # configure environment for WarehousePG
+ENV WHPG_REPO_URL=$GLOB_WHPG_REPO_URL
+ENV WHPG_REPO_TAG=$GLOB_WHPG_REPO_TAG
+ENV WHPG_BUILD_DIR=$GLOB_WHPG_BUILD_DIR
+ENV WHPG_INSTALL_DIR_PARENT=$GLOB_WHPG_INSTALL_DIR_PARENT
+ENV WHPG_INSTALL_DIR_NAME=$GLOB_WHPG_INSTALL_DIR_NAME
+ENV WHPG_INSTALL_DIR=$GLOB_WHPG_INSTALL_DIR
 ENV OS_NAME=$GLOB_OS_NAME
 ENV OS_VERSION=$GLOB_OS_VERSION
 ENV BUILD_VERSION=$GLOB_BUILD_VERSION
@@ -55,10 +69,6 @@ ENV WHPGHOME=$GLOB_WHPGHOME
 #ENV LD_LIBRARY_PATH=$WHPGHOME/lib:$LD_LIBRARY_PATH
 ENV MASTER_DATA_DIRECTORY=$GLOB_MASTER_DATA_DIRECTORY
 ENV PATH=$WHPGHOME/bin:$PATH
-
-
-# download setup.rpm.sh early on, which will fail early if the token doesn't work
-RUN --mount=type=secret,id=edbtoken_secret --mount=type=secret,id=edbrepository_secret curl -u token:$(cat /run/secrets/edbtoken_secret) -1sLf https://downloads.enterprisedb.com/basic/$(cat /run/secrets/edbrepository_secret)/setup.rpm.sh -o /root/setup.rpm.sh
 
 
 RUN sed -i s/mirror.centos.org/vault.centos.org/g /etc/yum.repos.d/*.repo
@@ -70,10 +80,19 @@ RUN sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|
 # install required packages for building WarehousePG
 #RUN localectl set-locale LANG=en_US.UTF-8
 RUN yum update -y
+RUN yum install -y centos-release-scl
+
+RUN sed -i s/mirror.centos.org/vault.centos.org/g /etc/yum.repos.d/*.repo
+RUN sed -i s/^#.*baseurl=http/baseurl=http/g /etc/yum.repos.d/*.repo
+RUN sed -i s/^mirrorlist=http/#mirrorlist=http/g /etc/yum.repos.d/*.repo
+RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
+RUN sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
+
+RUN yum update -y
+RUN yum install -y devtoolset-7
+RUN yum groupinstall -y "Development Tools"
 RUN yum install -y epel-release
 RUN yum update -y
-#RUN yum install -y sudo
-#RUN yum install -y passwd
 
 COPY rpm-packages-build-step.txt /root/rpm-packages-build-step.txt
 RUN yum install -y $(cat /root/rpm-packages-build-step.txt)
@@ -88,28 +107,47 @@ ENV LC_ALL=en_US.UTF-8
 RUN groupadd gpadmin
 RUN useradd -m -d /home/gpadmin -s /bin/bash -c "WarehousePG Database" -g gpadmin gpadmin
 RUN echo "gpadmin ALL=(ALL) NOPASSWD: ALL" | sudo EDITOR='tee -a' visudo
-
-
-# install the database from RPM
-RUN chmod u+x /root/setup.rpm.sh
-RUN /root/setup.rpm.sh
-
-# installation goes into /usr/local/greenplum-db-<version>,
-# and a symlink to /usr/local/greenplum-db is created
-RUN yum install -y warehouse-pg-6
-# clients are already included in the server package
-#RUN yum install -y warehouse-pg-clients
-# installation goes into /usr/local/bin
-RUN yum install -y whpg-backup
+RUN mkdir ${WHPG_BUILD_DIR} ${WHPG_INSTALL_DIR} && chown gpadmin:gpadmin ${WHPG_BUILD_DIR} ${WHPG_INSTALL_DIR}
 
 
 # switch to gpadmin user, do not build as root
 USER gpadmin
 
 
+# clone WarehousePG repository
+# --depth 1 (shallow clone, only need the branch tip to build) + retries:
+# a full clone of this repo's history is large enough that it repeatedly
+# dropped mid-transfer ("RPC failed", "early EOF") on a flaky connection.
+WORKDIR ${WHPG_BUILD_DIR}
+RUN for i in 1 2 3 4 5; do \
+      git clone --depth 1 --branch ${WHPG_REPO_TAG} ${WHPG_REPO_URL} . && break; \
+      echo "git clone attempt $i failed, retrying ..." >&2; \
+      rm -rf ${WHPG_BUILD_DIR}/* ${WHPG_BUILD_DIR}/.[!.]* 2>/dev/null; \
+      sleep 5; \
+    done
+RUN git checkout ${WHPG_REPO_TAG}
+
+# build WarehousePG Database from source
+#RUN ./configure --enable-debug --with-perl --with-python --with-libxml --with-openssl --prefix=${WHPG_INSTALL_DIR} --enable-orca --enable-pxf
+RUN . /opt/rh/devtoolset-7/enable ; ./configure --enable-debug --with-perl --with-python --with-libxml --with-openssl --prefix=${WHPG_INSTALL_DIR} --enable-orca --enable-pxf --with-uuid=e2fs --enable-cassert --disable-gpperfmon --with-gssapi --with-pam --with-ldap && make -j$(nproc)
+
+
+# this does NOT work in the build stage
+#RUN make check
+
+RUN sudo make install
+#RUN sudo make distclean
+
+
+RUN sudo bash -c "curl https://bootstrap.pypa.io/pip/2.7/get-pip.py | python"
+
+RUN sudo bash -c ". ${WHPGHOME}/greenplum_path.sh && pip install psycopg2"
+RUN sudo bash -c ". ${WHPGHOME}/greenplum_path.sh && pip install psutil"
+
+
 #######################################################################
 # database installed, but not started
-# build a new image, without the RPMs
+# build a new image, without the sources
 FROM centos:7 AS image-stage
 ENV container=docker
 
@@ -122,6 +160,12 @@ ARG GLOB_IMAGE_AUTHORS
 ARG GLOB_OS_NAME
 ARG GLOB_OS_VERSION
 ARG GLOB_BUILD_VERSION
+ARG GLOB_WHPG_REPO_URL
+ARG GLOB_WHPG_REPO_TAG
+ARG GLOB_WHPG_BUILD_DIR
+ARG GLOB_WHPG_INSTALL_DIR_PARENT
+ARG GLOB_WHPG_INSTALL_DIR_NAME
+ARG GLOB_WHPG_INSTALL_DIR
 ARG GLOB_WHPGHOME
 #ARG LD_LIBRARY_PATH
 ARG GLOB_MASTER_DATA_DIRECTORY
@@ -139,6 +183,12 @@ LABEL org.opencontainers.image.authors=$GLOB_IMAGE_AUTHORS
 ENV LANG=en_US.UTF-8
 ENV LC_ALL=en_US.UTF-8
 # configure environment for WarehousePG
+ENV WHPG_REPO_URL=$GLOB_WHPG_REPO_URL
+ENV WHPG_REPO_TAG=$GLOB_WHPG_REPO_TAG
+ENV WHPG_BUILD_DIR=$GLOB_WHPG_BUILD_DIR
+ENV WHPG_INSTALL_DIR_PARENT=$GLOB_WHPG_INSTALL_DIR_PARENT
+ENV WHPG_INSTALL_DIR_NAME=$GLOB_WHPG_INSTALL_DIR_NAME
+ENV WHPG_INSTALL_DIR=$GLOB_WHPG_INSTALL_DIR
 ENV OS_NAME=$GLOB_OS_NAME
 ENV OS_VERSION=$GLOB_OS_VERSION
 ENV BUILD_VERSION=$GLOB_BUILD_VERSION
@@ -162,7 +212,22 @@ RUN yum update -y
 COPY rpm-packages-image-step.txt /root/rpm-packages-image-step.txt
 RUN yum install -y $(cat /root/rpm-packages-image-step.txt)
 
+# systemd is PID 1 in this image (run the container like a real RHEL7 host)
+RUN yum install -y systemd
+
 RUN yum clean all
+
+# strip the units a container never needs (getty, login prompts, udev, etc.)
+# so the journal isn't full of failures for hardware that doesn't exist
+RUN (cd /lib/systemd/system/sysinit.target.wants/; \
+       for i in *; do [ "$i" = systemd-tmpfiles-setup.service ] || rm -f "$i"; done); \
+    rm -f /lib/systemd/system/multi-user.target.wants/*; \
+    rm -f /etc/systemd/system/*.wants/*; \
+    rm -f /lib/systemd/system/local-fs.target.wants/*; \
+    rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
+    rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
+    rm -f /lib/systemd/system/basic.target.wants/*; \
+    rm -f /lib/systemd/system/anaconda.target.wants/*
 
 ENV LANG=en_US.UTF-8
 ENV LC_ALL=en_US.UTF-8
@@ -185,30 +250,34 @@ EXPOSE 30000-30010/tcp
 
 
 # copy installation over from the build stage image
-# the warehouse-pg-6 RPM installs into /usr/edb/whpg6 and only places
-# symlinks (greenplum-db, greenplum-db-clients) into /usr/local, so both
-# trees must be copied or the symlinks dangle and all binaries go missing
-RUN rm -rf /usr/local/* /usr/edb/*
-COPY --from=build-stage /usr/local /usr/local
-COPY --from=build-stage /usr/edb /usr/edb
+RUN rm -rf ${WHPG_INSTALL_DIR_PARENT}/*
+COPY --from=build-stage ${WHPG_INSTALL_DIR_PARENT} ${WHPG_INSTALL_DIR_PARENT}
 
 
-# switch to gpadmin user, do not build image as root
-USER gpadmin
+# NOTE: unlike the tail-based image, we stay as root here.
+# systemd must run as PID 1 as root; gpadmin is re-entered via the
+# warehousepg.service unit's "User=gpadmin".
 
 # Create data directories
-RUN sudo mkdir -p /whpgdata/master /whpgdata/segments /whpgdata/segments/whpgdata1 /whpgdata/segments/whpgdata2 && \
-    sudo chown -R gpadmin:gpadmin /whpgdata
+RUN mkdir -p /whpgdata/master /whpgdata/segments /whpgdata/segments/whpgdata1 /whpgdata/segments/whpgdata2 && \
+    chown -R gpadmin:gpadmin /whpgdata
 
 
 COPY --chown=gpadmin:gpadmin hostfile_whpginitsystem6 /home/gpadmin/hostfile_whpginitsystem
 COPY --chown=gpadmin:gpadmin whpginitsystem_singlenode6 /home/gpadmin/whpginitsystem_singlenode
 # the chmod option needs buildx
 COPY --chown=gpadmin:gpadmin --chmod=0750 warehousepg_init6.sh /home/gpadmin/warehousepg_init.sh
-COPY --chown=gpadmin:gpadmin --chmod=0750 cmd.sh /home/gpadmin/cmd.sh
+
+# systemd-managed WarehousePG: a first-boot prep script + a unit that
+# runs gpinitsystem (first boot) or gpstart (subsequent boots) as gpadmin
+COPY --chmod=0755 warehousepg-setup.sh /usr/local/bin/warehousepg-setup.sh
+COPY --chmod=0755 warehousepg-poststart.sh /usr/local/bin/warehousepg-poststart.sh
+COPY warehousepg.service /etc/systemd/system/warehousepg.service
+RUN systemctl enable sshd.service warehousepg.service
+
 WORKDIR /home/gpadmin
 
+# clean systemd shutdown on `docker stop` -> triggers warehousepg.service ExecStop (gpstop)
+STOPSIGNAL SIGRTMIN+3
 
-#CMD ["bash"]
-#CMD ["tail", "-f", "/dev/null"]
-CMD ["/home/gpadmin/cmd.sh"]
+CMD ["/usr/sbin/init"]
